FROM node:alpine

WORKDIR /usr/app

COPY package.json .

RUN npm i 

COPY . .

CMD ["npm","run","start"]

# docker run -it -p 3000:3000 -v /usr/app/node_modules -v $(pwd):/usr/app 123d938a57b5
#frontend_react-app:latest e4f0b31425d6